// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdFgxLR_pGwU4taCvkJwbfdkwMa-WQDFw',
    appId: '1:740606240594:web:51f500ade8a9e01772bc8b',
    messagingSenderId: '740606240594',
    projectId: 'lastoptiscan',
    authDomain: 'lastoptiscan.firebaseapp.com',
    storageBucket: 'lastoptiscan.appspot.com',
    measurementId: 'G-E7GF82BGPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgAyXOpqY7XMBLl9L96mlZLX8kn26W4s',
    appId: '1:740606240594:android:c468c6fdc10760c872bc8b',
    messagingSenderId: '740606240594',
    projectId: 'lastoptiscan',
    storageBucket: 'lastoptiscan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3PopxxhwncLvshiM5NwW4dlh1wIwDhRM',
    appId: '1:740606240594:ios:02c90307247d734c72bc8b',
    messagingSenderId: '740606240594',
    projectId: 'lastoptiscan',
    storageBucket: 'lastoptiscan.appspot.com',
    iosBundleId: 'com.example.optiscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3PopxxhwncLvshiM5NwW4dlh1wIwDhRM',
    appId: '1:740606240594:ios:02c90307247d734c72bc8b',
    messagingSenderId: '740606240594',
    projectId: 'lastoptiscan',
    storageBucket: 'lastoptiscan.appspot.com',
    iosBundleId: 'com.example.optiscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdFgxLR_pGwU4taCvkJwbfdkwMa-WQDFw',
    appId: '1:740606240594:web:c560df9c3d705aff72bc8b',
    messagingSenderId: '740606240594',
    projectId: 'lastoptiscan',
    authDomain: 'lastoptiscan.firebaseapp.com',
    storageBucket: 'lastoptiscan.appspot.com',
    measurementId: 'G-6L8X1KYWXY',
  );
}
